LSDSHW3_v3: LSDSHW3_v3.o Queries_HT.o
	g++ LSDSHW3_v3.o Queries_HT.o -o LSDSHW3_v3
	
LSDS_HW2.o: LSDSHW3_v3.cpp
	g++ -c LSDSHW3_v3.cpp
	
Queries_HT.o: Queries_HT.cpp Queries_HT.h
	g++ -c Queries_HT.cpp
	
clean:
	rm *.o