LSDSHW5: LSDSHW5.o Prefix_Trie.o
	g++ LSDSHW5.o Prefix_Trie.o -o LSDSHW5
	
LSDSHW5.o: LSDSHW5.cpp
	g++ -c LSDSHW5.cpp
	
Prefix_Trie.o: Prefix_Trie.cpp Prefix_Trie.h
	g++ -c Prefix_Trie.cpp
	
clean:
	rm *.o